### ISSUE TITLE
Can't make player.html example to decode ac3 sound

### ISSUE THREAD

**Issue by hellozyemlya** [Yahweasel/transavormer#4]
I build custom lbav.js with ac3 decoder. Also, I included ../node_modules/libavjs-webcodecs-polyfill/dist/libavjs-webcodecs-polyfill.js. But seems like transvormer still using native AudioDecoder. Is it possible to mix audio decoder from libavjs and use webcodecs video decoder?

**Comment by hellozyemlya** [comment]
I managed to workaround that by this lines:
```
        await LibAVWebCodecs.load({LibAV: LibAV})
        window.AudioDecoder = LibAVWebCodecs.AudioDecoder
```
before transavormer init.
Also this patch
```
                const data = new Uint8Array(chunk.byteLength)
                chunk.copyTo(data)
``` 
was required in libavjs-webcodecs-polyfill audio decoder instead of _libavGetData call(maybe my polyfill version is outdated?).
After that it was able to decode and play mkv with ac3 audio, but sound is broken a little bit, specially when it is 5.1 sound. I transcoded it by ffmpeg to 2.0 ac3, it is better(at least I can distinguish words), but still broken.

**Comment by Yahweasel** [comment]
I definitely did a big dumb in TransAVormer. It doesn't correctly check whether WebCodecs actually supports the codec in question, and blindly tries anyway :zany_face: . It's not designed to work with the polyfill, and in fact, you shouldn't use it with the polyfill; it's supposed to directly use libav.js when possible. Knowing that that check is missing, it's easy enough to add. Note that TransAVormer hasn't even had release 0.0.1 yet, so things are expected to be broken still :shrug: 

As per the weird sound, the player demonstration has no capacity to adapt to the number of output channels, so unless you add an explicit filter to do so, the mapping is just to drop most channels. Quite useless. I suppose it makes more sense for the playback filter to also map channels correctly, but long story short, the channel mapping is not part of that demonstration, though it is a necessary part of any real player.

**Comment by Yahweasel** [comment]
(Oh, and just to explain the "needed" patch in the polyfill, that's what happens when you mix real WebCodecs packets with the polyfill decoder. You need to create packets and decode them with the same implementation; you cannot mix and match. But that's why TransAVormer is not designed to be compatible with the polyfill.)

**Comment by hellozyemlya** [comment]
Ahh, I see. Will try to find that place where check must be performed. Actually. But it strange, it seems like polyfill types used everywhere. Or I maybe missed something...

**Comment by hellozyemlya** [comment]
ps: I guess it is in _init method. Will try to remove tryAudioDecoder whole part to ensure it callbacks to libav for audio by default. Wanna see if my 2.0 ac3 will work fine or not.

**Comment by hellozyemlya** [comment]
Btw, how to add filter? Is there some way to do that with existing api?

**Comment by Yahweasel** [comment]
> Ahh, I see. Will try to find that place where check must be performed. Actually. But it strange, it seems like polyfill types used everywhere. Or I maybe missed something...

The polyfill types are used everywhere because TypeScript does not have public definitions of the audio WebCodecs types, at least not as of the last time I checked. The polyfill is used *only* for its types.

**Comment by Yahweasel** [comment]
> ps: I guess it is in _init method. Will try to remove tryAudioDecoder whole part to ensure it callbacks to libav for audio by default. Wanna see if my 2.0 ac3 will work fine or not.

I haven't yet checked (will check when it's not the weekend), but I'm not confident that I implemented the necessary alternative correctly. The decoder type takes either a WebCodecs description or a libav description, and I don't recall if I actually performed the conversion necessary for when WebCodecs doesn't work. The correct fix will be checking whether WebCodecs accepts the configuration, and if not, converting it to a libav.js configuration.

**Comment by hellozyemlya** [comment]
> ps: I guess it is in _init method. Will try to remove tryAudioDecoder whole part to ensure it callbacks to libav for audio by default. Wanna see if my 2.0 ac3 will work fine or not.

Yay, it works. 

I guess there is try, but not catch. Interesting if that will fail-fast on Video\Audio codec creation.

**Comment by Yahweasel** [comment]
> Btw, how to add filter? Is there some way to do that with existing api?

The "la-filter" type. I don't recall off the top of my head what libav filter is needed to perform this kind of channel mixing.

**Comment by Yahweasel** [comment]
> > ps: I guess it is in _init method. Will try to remove tryAudioDecoder whole part to ensure it callbacks to libav for audio by default. Wanna see if my 2.0 ac3 will work fine or not.
> 
> Yay, it works.
> 
> I guess there is try, but not catch. Interesting if that will fail-fast on Video\Audio codec creation.

Interesting. I guess I just missed one path thru. Ugh.

**Comment by hellozyemlya** [comment]
With this patch it plays my ac3 audio.
```
Index: src/decoder.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/decoder.ts b/src/decoder.ts
--- a/src/decoder.ts	(revision 44f1b1fc99f567df5c2c7263a8f1a33b3fe94a1a)
+++ b/src/decoder.ts	(date 1734817428444)
@@ -90,14 +90,15 @@
                 }
 
             } else if (stream.codec_type === la.AVMEDIA_TYPE_AUDIO) {
-                const wcd = await tryAudioDecoder(
-                    la, streamIndex, stream, decodeQueue, setDecodeErr
-                );
-                if (wcd) {
-                    decoders.push(wcd);
-                    destructors.push(async () => wcd.close());
-                    continue;
-                }
+                // drop for libav
+                // const wcd = await tryAudioDecoder(
+                //     la, streamIndex, stream, decodeQueue, setDecodeErr
+                // );
+                // if (wcd) {
+                //     decoders.push(wcd);
+                //     destructors.push(async () => wcd.close());
+                //     continue;
+                // }
 
             } else {
                 // Unsupported stream type
```
Will check later if it can be wrapped to try\catch.

**Comment by hellozyemlya** [comment]
This works for audio. I guess same will work for video. Will check that with other proprietary codecs.
```
Index: src/decoder.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/decoder.ts b/src/decoder.ts
--- a/src/decoder.ts	(revision 44f1b1fc99f567df5c2c7263a8f1a33b3fe94a1a)
+++ b/src/decoder.ts	(date 1734818595077)
@@ -343,6 +343,9 @@
 ) {
     try {
         const config = await lawc.audioStreamToConfig(la, stream);
+        if(config.codec === 'unknown') {
+          return null
+        }
         const dec = new AudioDecoder({
             output: x => decodeQueue.push({
                 streamIndex: streamIndex,

```

**Comment by hellozyemlya** [comment]
> > Ahh, I see. Will try to find that place where check must be performed. Actually. But it strange, it seems like polyfill types used everywhere. Or I maybe missed something...
> 
> The polyfill types are used everywhere because TypeScript does not have public definitions of the audio WebCodecs types, at least not as of the last time I checked. The polyfill is used _only_ for its types.

`// Best we can do is a libavjs-webcodecs-polyfill-specific config` this comment is miss-leading, where codec is assigned to {libavjs: ...} object instead of string.

Also, I guess this is a types you trying to find - https://www.npmjs.com/package/@types/dom-webcodecs. I guess if transavormer want to use polyfilled webcodecs, it must do it transparently, without relying on any of polyfilled types at all.

**Comment by Yahweasel** [comment]
> > The polyfill types are used everywhere because TypeScript does not have public definitions of the audio WebCodecs types, at least not as of the last time I checked. The polyfill is used _only_ for its types.
> 
> `// Best we can do is a libavjs-webcodecs-polyfill-specific config` this comment is miss-leading, where codec is assigned to {libavjs: ...} object instead of string.
> 

My statement was about TransAVormer, not libavjs-webcodecs-bridge.

**Comment by hellozyemlya** [comment]
Yeah, my bad.

**Comment by hellozyemlya** [comment]
Opened MR, works perfectly with many junk codecs on my side. Still, there is some memory leak, will open another bug once investigated.

**Comment by hellozyemlya** [comment]
Issue resolved. Closing this. Many thanks.
